services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d webapp"]
      interval: 1s
      timeout: 5s
      retries: 5

  migrate:
    image: upgrade-checker:local
    command: sh -c "pnpm db:migrate"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/webapp
    depends_on:
      db:
        condition: service_healthy

  webapp:
    image: upgrade-checker:local
    env_file:
      - webapp/.env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/webapp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data: