name: WebApp
on:
  push:
    branches:
      - "**"
env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  NODE_OPTIONS: "--no-deprecation"
  ALLOW_INDEXING: false
  LOG_LEVEL: debug
  ETH_NETWORK: "mainnet"
  DATABASE_URL: postgresql://user:password@localhost:5432/webapp
  NODE_ENV: development
  L1_RPC_URL: ${{ secrets.TENDERLY_RPC_URL }}
  L1_RPC_URL_FOR_UPGRADES: http://127.0.0.1:8545
  AUTH_SECRET: sososecret
  UPGRADE_HANDLER_ADDRESS: 0xd88ce7170eac2aad76acc74bda448c512818a2d4

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - name: Start DB
        run: |
          ./scripts/init-db.sh
          docker ps -a

      - name: Build WebApp
        run: pnpm build

